//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class category
    {
        public category()
        {
            this.workouts = new HashSet<workout>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Category name reqired", AllowEmptyStrings = false)]
        public string name { get; set; }
        [Required(ErrorMessage = "Description reqired", AllowEmptyStrings = false)]
        public string description { get; set; }
        [ConcurrencyCheck]
        public byte[] timestamp { get; set; }
    
        public virtual ICollection<workout> workouts { get; set; }
    }
}
