//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string message { get; set; }
        public byte[] timestamp { get; set; }
        public int User_id { get; set; }
        public int Workout_id { get; set; }
        public System.DateTime date_cteated { get; set; }
    
        public virtual user user { get; set; }
        public virtual workout workout { get; set; }
    }
}
