//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class exercise
    {
        public exercise()
        {
            this.workout_exercise = new HashSet<workout_exercise>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Type reqired", AllowEmptyStrings = false)]
        public int type_id { get; set; }
        [Required(ErrorMessage = "User reqired", AllowEmptyStrings = false)]
        public int created_by_user_id { get; set; }
        [Required(ErrorMessage = "Creation date reqired", AllowEmptyStrings = false)]
        public System.DateTime created_at { get; set; }
        public string link { get; set; }
        [Required(ErrorMessage = "Description reqired", AllowEmptyStrings = false)]
        public string description { get; set; }
        [ConcurrencyCheck]
        public byte[] timestamp { get; set; }
        [Required(ErrorMessage = "Exercise name reqired", AllowEmptyStrings = false)]
        public string name { get; set; }
    
        public virtual type type { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<workout_exercise> workout_exercise { get; set; }
    }
}
