//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercise
    {
        public exercise()
        {
            this.user_favorite_exercise = new HashSet<user_favorite_exercise>();
            this.workout_exercise = new HashSet<workout_exercise>();
        }
    
        public int id { get; set; }
        public int type_id { get; set; }
        public int created_by_user_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string link { get; set; }
        public string description { get; set; }
        public System.DateTime timestamp { get; set; }
        public string name { get; set; }
    
        public virtual type type { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<user_favorite_exercise> user_favorite_exercise { get; set; }
        public virtual ICollection<workout_exercise> workout_exercise { get; set; }
    }
}
