//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public type()
        {
            this.exercises = new HashSet<exercise>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string measure { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual ICollection<exercise> exercises { get; set; }
    }
}
