//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class type
    {
        public type()
        {
            this.exercises = new HashSet<exercise>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Type name reqired", AllowEmptyStrings = false)]
        public string name { get; set; }
        [Required(ErrorMessage = "Measure reqired", AllowEmptyStrings = false)]
        public string measure { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual ICollection<exercise> exercises { get; set; }
    }
}
