//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_favorite_exercise
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public int Exercise_id { get; set; }
    
        public virtual exercise exercise { get; set; }
        public virtual user user { get; set; }
    }
}
