//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user_favorite_workout
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int workout_id { get; set; }
        [ConcurrencyCheck]
        public byte[] timestamp { get; set; }
    
        public virtual user user { get; set; }
        public virtual workout workout { get; set; }
    }
}
