//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user_workout
    {
        public int id { get; set; }
        [Required(ErrorMessage = "No user_id given")]
        public int user_id { get; set; }
        [Required(ErrorMessage = "No workout_id given")]
        public int workout_id { get; set; }
        public int number_of_ex_completed { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_finished { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual user user { get; set; }
        public virtual workout workout { get; set; }
    }
}
