//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout_rating
    {
        public int workout_id { get; set; }
        public decimal average_rating { get; set; }
        public int times_rated { get; set; }
    
        public virtual workout workout { get; set; }
    }
}
