USE [master]
GO

/****** Object:  Database [gofitdb]    Script Date: 06/10/2015 08:57:14 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'gofitdb')
DROP DATABASE [gofitdb]
GO

USE [master]
GO

/****** Object:  Database [gofitdb]    Script Date: 06/10/2015 08:57:14 ******/
CREATE DATABASE [gofitdb] ON  PRIMARY 
( NAME = N'gofitdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\gofitdb.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'gofitdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\gofitdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [gofitdb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gofitdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gofitdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gofitdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gofitdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gofitdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gofitdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [gofitdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gofitdb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [gofitdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gofitdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gofitdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gofitdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gofitdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gofitdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gofitdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gofitdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gofitdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gofitdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gofitdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gofitdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gofitdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gofitdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gofitdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gofitdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gofitdb] SET  READ_WRITE 
GO

ALTER DATABASE [gofitdb] SET RECOVERY FULL 
GO

ALTER DATABASE [gofitdb] SET  MULTI_USER 
GO

ALTER DATABASE [gofitdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gofitdb] SET DB_CHAINING OFF 
GO

